// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// nn_counts_cpp
IntegerMatrix nn_counts_cpp(NumericVector x, NumericVector y, NumericVector radii);
RcppExport SEXP _permfreeG_nn_counts_cpp(SEXP xSEXP, SEXP ySEXP, SEXP radiiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type radii(radiiSEXP);
    rcpp_result_gen = Rcpp::wrap(nn_counts_cpp(x, y, radii));
    return rcpp_result_gen;
END_RCPP
}
// censored_neighbor_counts_cpp
IntegerMatrix censored_neighbor_counts_cpp(NumericVector x, NumericVector y, NumericVector bdist, NumericVector radii);
RcppExport SEXP _permfreeG_censored_neighbor_counts_cpp(SEXP xSEXP, SEXP ySEXP, SEXP bdistSEXP, SEXP radiiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type bdist(bdistSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type radii(radiiSEXP);
    rcpp_result_gen = Rcpp::wrap(censored_neighbor_counts_cpp(x, y, bdist, radii));
    return rcpp_result_gen;
END_RCPP
}
// csr_uni_moments_cpp
List csr_uni_moments_cpp(NumericVector x, NumericVector y, NumericVector radii, int n_subset, bool covariance);
RcppExport SEXP _permfreeG_csr_uni_moments_cpp(SEXP xSEXP, SEXP ySEXP, SEXP radiiSEXP, SEXP n_subsetSEXP, SEXP covarianceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type radii(radiiSEXP);
    Rcpp::traits::input_parameter< int >::type n_subset(n_subsetSEXP);
    Rcpp::traits::input_parameter< bool >::type covariance(covarianceSEXP);
    rcpp_result_gen = Rcpp::wrap(csr_uni_moments_cpp(x, y, radii, n_subset, covariance));
    return rcpp_result_gen;
END_RCPP
}
// csr_cross_moments_cpp
List csr_cross_moments_cpp(NumericVector x, NumericVector y, NumericVector radii, int n_i, int n_j, bool covariance);
RcppExport SEXP _permfreeG_csr_cross_moments_cpp(SEXP xSEXP, SEXP ySEXP, SEXP radiiSEXP, SEXP n_iSEXP, SEXP n_jSEXP, SEXP covarianceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type radii(radiiSEXP);
    Rcpp::traits::input_parameter< int >::type n_i(n_iSEXP);
    Rcpp::traits::input_parameter< int >::type n_j(n_jSEXP);
    Rcpp::traits::input_parameter< bool >::type covariance(covarianceSEXP);
    rcpp_result_gen = Rcpp::wrap(csr_cross_moments_cpp(x, y, radii, n_i, n_j, covariance));
    return rcpp_result_gen;
END_RCPP
}
// rs_moments_cpp
List rs_moments_cpp(NumericVector x, NumericVector y, NumericVector bdist, NumericVector radii, int n_i, int n_j);
RcppExport SEXP _permfreeG_rs_moments_cpp(SEXP xSEXP, SEXP ySEXP, SEXP bdistSEXP, SEXP radiiSEXP, SEXP n_iSEXP, SEXP n_jSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type bdist(bdistSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type radii(radiiSEXP);
    Rcpp::traits::input_parameter< int >::type n_i(n_iSEXP);
    Rcpp::traits::input_parameter< int >::type n_j(n_jSEXP);
    rcpp_result_gen = Rcpp::wrap(rs_moments_cpp(x, y, bdist, radii, n_i, n_j));
    return rcpp_result_gen;
END_RCPP
}
// counts_within_bdist_cpp
IntegerVector counts_within_bdist_cpp(NumericVector x, NumericVector y, NumericVector bdist);
RcppExport SEXP _permfreeG_counts_within_bdist_cpp(SEXP xSEXP, SEXP ySEXP, SEXP bdistSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type bdist(bdistSEXP);
    rcpp_result_gen = Rcpp::wrap(counts_within_bdist_cpp(x, y, bdist));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_permfreeG_nn_counts_cpp", (DL_FUNC) &_permfreeG_nn_counts_cpp, 3},
    {"_permfreeG_censored_neighbor_counts_cpp", (DL_FUNC) &_permfreeG_censored_neighbor_counts_cpp, 4},
    {"_permfreeG_csr_uni_moments_cpp", (DL_FUNC) &_permfreeG_csr_uni_moments_cpp, 5},
    {"_permfreeG_csr_cross_moments_cpp", (DL_FUNC) &_permfreeG_csr_cross_moments_cpp, 6},
    {"_permfreeG_rs_moments_cpp", (DL_FUNC) &_permfreeG_rs_moments_cpp, 6},
    {"_permfreeG_counts_within_bdist_cpp", (DL_FUNC) &_permfreeG_counts_within_bdist_cpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_permfreeG(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
