# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Neighbour counts within each radius (<= r)
#'
#' @param x,y Point coordinates.
#' @param radii Radii (must be increasing for the binary-search fast path; any
#'   order is accepted).
#' @return An \code{N x length(radii)} integer matrix.
#' @keywords internal
nn_counts_cpp <- function(x, y, radii) {
    .Call(`_permfreeG_nn_counts_cpp`, x, y, radii)
}

#' Neighbour counts within min(radius, boundary distance)
#'
#' Used by the Hanisch and Kaplan-Meier moment calculations: an event is only
#' observed when its nearest-neighbour distance does not exceed the point's
#' distance to the window boundary.
#'
#' @param x,y Point coordinates.
#' @param bdist Distance of each point to the window boundary.
#' @param radii Radii.
#' @return An \code{N x length(radii)} integer matrix with entry
#'   \eqn{\#\{q \ne p : d_{pq} \le \min(r_k, b_p)\}}.
#' @keywords internal
censored_neighbor_counts_cpp <- function(x, y, bdist, radii) {
    .Call(`_permfreeG_censored_neighbor_counts_cpp`, x, y, bdist, radii)
}

#' Exact univariate CSR mean and variance
#'
#' @param x,y Point coordinates of the full pattern.
#' @param radii Radii at which to evaluate the moments.
#' @param n_subset Number of marked points selected in each random subset.
#' @param covariance Include the off-diagonal covariance terms (exact variance)
#'   or only the marginal term (independence approximation).
#' @return A list with numeric vectors \code{mean} and \code{var}.
#' @keywords internal
csr_uni_moments_cpp <- function(x, y, radii, n_subset, covariance = TRUE) {
    .Call(`_permfreeG_csr_uni_moments_cpp`, x, y, radii, n_subset, covariance)
}

#' Exact bivariate Gcross CSR mean and variance
#'
#' Disjoint label-permutation null: type-i set of size \code{n_i}, type-j set
#' of size \code{n_j} drawn without replacement from the remaining locations.
#'
#' @param x,y Point coordinates of the full pattern.
#' @param radii Radii at which to evaluate the moments.
#' @param n_i Number of type-i points in each permutation.
#' @param n_j Number of type-j points in each permutation.
#' @param covariance Include the off-diagonal covariance terms (exact variance)
#'   or only the marginal term.
#' @return A list with numeric vectors \code{mean} and \code{var}.
#' @keywords internal
csr_cross_moments_cpp <- function(x, y, radii, n_i, n_j, covariance = TRUE) {
    .Call(`_permfreeG_csr_cross_moments_cpp`, x, y, radii, n_i, n_j, covariance)
}

#' Reduced-sample (border) CSR moments
#'
#' Exact first and second moments of the numerator Z and denominator Y of the
#' reduced-sample estimator \eqn{\hat G_{rs}(r) = Z/Y}, combined into the
#' ratio-of-expectations mean and a first-order (delta method) variance.
#'
#' @param x,y Point coordinates of the full pattern.
#' @param bdist Distance from each point to the window boundary.
#' @param radii Radii at which to evaluate the moments.
#' @param n_i Size of the randomly selected subset (type-i set for cross).
#' @param n_j For bivariate Gcross the size of the type-j set; use \code{-1}
#'   for univariate Gest.
#' @return A list with \code{mean}, \code{var} and the raw components
#'   \code{z_mean}, \code{z_var}, \code{y_mean}, \code{y_var}, \code{cov}.
#' @keywords internal
rs_moments_cpp <- function(x, y, bdist, radii, n_i, n_j = -1L) {
    .Call(`_permfreeG_rs_moments_cpp`, x, y, bdist, radii, n_i, n_j)
}

#' Number of neighbours closer than the window boundary
#'
#' For each point p, the number of other points q whose distance to p is at
#' most the boundary distance b_p.  Used by the
#' Kaplan-Meier / Hanisch mean-field moment calculations.
#'
#' @param x,y Point coordinates.
#' @param bdist Distance of each point to the window boundary.
#' @return Integer vector with one entry per point.
#' @keywords internal
counts_within_bdist_cpp <- function(x, y, bdist) {
    .Call(`_permfreeG_counts_within_bdist_cpp`, x, y, bdist)
}

